### ISSUE TITLE
Allow lowering/increasing shadow map resolution

### ISSUE THREAD

**Issue by notfoundname** [spiralhalo/ecos#1]
Hello, not sure if this will be visible.
These shaders look great and perform well on my cheap laptop. However, I would like to suggest to add some kind of slider for changing shadow map resolution, if that's possible. Changing values by myself led to visual artifacts.
Thanks

**Comment by spiralhalo** [comment]
Hello, thanks for using ecos.
What value did you change? And what values did you try? I suggest powers of two such as 128, 256, 512, 1024.
I can add a slider in the next version of ecos, just curious what number works best for you.

**Comment by spiralhalo** [comment]
By the way, was changing shadow resolution meant to increase performance? I tried several low resolution shadow, but it didn't look very good.

In fact it was probably causing the "visual artifacts" that you mentioned. I could add a filter to counteract the artifacts, but the filter itself would cost performance (although from my testing, it still results in a net performance boost at 1080p, but not much to be "worth it"). It does seem to boost performance at lower game resolution (800x600 or less), so it might be worth adding in the end.

**Comment by spiralhalo** [comment]
v1.2 has been released to address a bug and it contains a shadow quality selector. please try that and give feedback. Thanks

https://modrinth.com/shader/ecos/version/v1.2
